import { Box, Container, Flex, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { CustomContainer } from "../components/layout/container";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CustomContainer>
                <Text>main</Text>
            </CustomContainer>
        </>
    );
};

export default Home;
